Control color of LED
TNTrol/ESTC-project pull request #17
Opened 2021-11-22 09:16 UTC by TNTrol

2021-11-22 12:26 UTC, Diadlo requested changes

2021-11-22 12:26 UTC, Diadlo commented on button_module/button_module.c
> +    m_operation ^= 0x1;
При чтении кода не очевидно, что это за операции, почему в каждой ветке делается то или иное действие.
Возможно стоит сравнивать значение `m_operation` с именованными константами?
Во-первых, тогда будет понятно, что `m_operation` характерезует текущее изменение состояния кнопки.
Во-вторых, будет понятнее, почему в одной ветке мы рассматриваем клик, а в другой меняем флаг долгого нажатия

2021-11-22 12:26 UTC, Diadlo commented on button_module/button_module.c
> +static nrfx_gpiote_evt_handler_t m_evt_handler = NULL;
Судя по всему это обработчик именно двойного клика, стоит отразить в названии

2021-11-22 12:26 UTC, Diadlo commented on button_module/button_module.c
> +static volatile uint8_t m_operation = 0;
Рассмотрите возможность объединить блоки переменный в структуру

2021-11-22 12:26 UTC, Diadlo commented on button_module/button_module.c
>  void init_gpiote_button(nrfx_gpiote_evt_handler_t evt_handler)
Название параметра не отражает, что это именно для двойного клика

2021-11-22 12:26 UTC, Diadlo commented on button_module/button_module.c
> +static volatile bool m_freeze = false;
Кажется эта переменная не используется

2021-11-22 12:26 UTC, Diadlo commented on button_module/button_module.c
> +static volatile bool m_long = false;
Переменные типа bool часто (но не всегда) рекомендуется именовать в форме вопроса. Действительно, чтобы было понятно, что значит true и false в значении данной переменной.
В данном случае флаг просто отображает факт нажатия кнопки, так ведь?
Если вы все равно используете polling значения переменной `m_long` через функцию `is_long_press`, то можно полить сразу GPIO минуя этот флаг. Ну это так, чисто для справки

2021-11-22 12:26 UTC, Diadlo commented on color_module/color_module.c
> + uint32_t region, remainder, p, q, t;
Немного форматирование поехало

2021-11-22 12:26 UTC, Diadlo commented on color_module/color_module.c
> +void hsv_to_rgb(hsv_t *hsv, rgb_t *rgb)
`hsv` не меняется. Лучше сделать const, чтобы извне функции было понятно, что значение используется только для чтения

2021-11-22 12:26 UTC, Diadlo commented on color_module/color_module.c
> +            rgb->r = hsv->v; rgb->g = t; rgb->b = p;
Большинство кодовых стандартов требует, чтобы было по одной операции на строку, лучше не писать код в одну строку

2021-11-22 12:26 UTC, Diadlo commented on util_module/utils.h
> +}modificator_t;
Лучше делать общий префикс, а не суффикс. Это визуально группирует все значения enum

2021-11-22 12:26 UTC, Diadlo commented on main.c
> +    m_state = m_state == V_MOD ? NONE : m_state + 1;
Тут есть потенциал для улучшения. Если вы делаете кольцевую итерацию по таким вещам как режимы, что вы будете делать, если добавится режим в конец или в начало? Точно ли вы не забудете обновить `V_MOD` везде, где он именно отвечает за последний режим?
```
typedef enum {
    MOD_FIRST,
    MOD_NONE = MOD_FIRST,
    MOD_H,
    MOD_S,
    MOD_V,
    MOD_LAST = MOD_V
} modificator_t;
```

Можно сделать так и ссылаться на `MOD_FIRST` и `MOD_LAST`. Форма записи может разниться, но суть такая.

2021-11-22 12:26 UTC, Diadlo commented on main.c
> +        set_value_of_channel(&m_pwm ,m_phase >> 1, MAX_TIME_PWM_CICLE);
Запятая поехала

2021-11-22 12:26 UTC, Diadlo commented on main.c
> +    if (!m_state)
Если у вас переменная имеет тип не bool, то лучше использовать явное сравнение `if (m_state == NONE)`

2021-11-22 12:26 UTC, Diadlo commented on main.c
> +    uint32_t r = m_rgb_color.r * step, g = m_rgb_color.g * step, b = m_rgb_color.b * step;
Будье осторожны с несколькими операциями в одной строке

2021-11-22 12:26 UTC, Diadlo commented on main.c
> +        if(m_state && is_long_press())
Лучше использовать явное сравнение

2021-11-22 12:26 UTC, Diadlo commented on main.c
> +            NRF_LOG_INFO("State %d Color r=%d, g=%d, b=%d", m_state, m_rgb_color.r, m_rgb_color.g, m_rgb_color.b);
Будьте осторожны с массовым логгированием. Может вызывать побочный эффект в виде задержек

2021-11-22 12:26 UTC, Diadlo commented on main.c
> +                h = h == 1023 ? 0 : h + 1;
1. Рассмотрите возможность написать функцию для ротации значения
2. Стоит минимизировать количество безымянных цисел в коде

2021-11-22 12:26 UTC, Diadlo commented on pwm_module/pwm_module.c
> +#define UNMASK(s, n) ((s >> n) & 1 ? NRFX_PWM_PIN_INVERTED : NRFX_PWM_PIN_NOT_USED)
`s` и `n` в выражении тоже надо обернуть в скобки. Иначе вы можете получить проблему с приоритетом операций. Например `UNMASK(flag ? a : b, c)` станет `(flag ? a : b >> c) ...` и битовый сдвиг применится только к `b`, а не к результату тернарного оператора.

2021-11-22 16:50 UTC, TNTrol commented on button_module/button_module.c
> +static volatile uint8_t m_operation = 0;
структура для хранения контекста кнопки 
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/button_module/button_module.h#L29

использование 
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/button_module/button_module.c#L3

2021-11-22 16:52 UTC, TNTrol commented on button_module/button_module.c
>  void init_gpiote_button(nrfx_gpiote_evt_handler_t evt_handler)
Исправил 
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/button_module/button_module.c#L41

2021-11-22 16:52 UTC, TNTrol commented on button_module/button_module.c
> +static volatile bool m_freeze = false;
Удалил

2021-11-22 16:57 UTC, TNTrol commented on util_module/utils.h
> +}modificator_t;
Исправил

2021-11-22 16:59 UTC, TNTrol commented on button_module/button_module.c
> +static volatile bool m_long = false;
Исправлено в новых комитах

2021-11-22 17:00 UTC, TNTrol commented on color_module/color_module.c
> + uint32_t region, remainder, p, q, t;
Исправил
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/color_module/color_module.c#L3

2021-11-22 17:00 UTC, TNTrol commented on color_module/color_module.c
> +void hsv_to_rgb(hsv_t *hsv, rgb_t *rgb)
Исправил
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/color_module/color_module.c#L3

2021-11-22 17:01 UTC, TNTrol commented on color_module/color_module.c
> +            rgb->r = hsv->v; rgb->g = t; rgb->b = p;
Исправил 
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/color_module/color_module.c#L22

2021-11-22 17:04 UTC, TNTrol commented on main.c
> +    m_state = m_state == V_MOD ? NONE : m_state + 1;
Дополнил структуру 
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/util_module/utils.h#L13
Сделал инкрементацию с помощью макроса
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/util_module/utils.h#L5
Использование
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/main.c#L35

2021-11-22 17:04 UTC, TNTrol commented on main.c
> +        set_value_of_channel(&m_pwm ,m_phase >> 1, MAX_TIME_PWM_CICLE);
Исправил

2021-11-22 17:05 UTC, TNTrol commented on main.c
> +    if (!m_state)
Исправил
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/main.c#L63

2021-11-22 17:05 UTC, TNTrol commented on main.c
> +    uint32_t r = m_rgb_color.r * step, g = m_rgb_color.g * step, b = m_rgb_color.b * step;
Форматировал вот так
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/main.c#L94

2021-11-22 17:06 UTC, TNTrol commented on main.c
> +        if(m_state && is_long_press())
Исправил
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/main.c#L118

2021-11-22 17:06 UTC, TNTrol commented on main.c
> +            NRF_LOG_INFO("State %d Color r=%d, g=%d, b=%d", m_state, m_rgb_color.r, m_rgb_color.g, m_rgb_color.b);
Понимаю, но в данном случае удобно наблюдать за составляющей rgb

2021-11-22 17:07 UTC, TNTrol commented on main.c
> +                h = h == 1023 ? 0 : h + 1;
Реализовал макрос
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/util_module/utils.h#L4
Использование
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/main.c#L124

2021-11-22 17:08 UTC, TNTrol commented on pwm_module/pwm_module.c
> +#define UNMASK(s, n) ((s >> n) & 1 ? NRFX_PWM_PIN_INVERTED : NRFX_PWM_PIN_NOT_USED)
Исправил
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/pwm_module/pwm_module.c#L5

2021-11-22 17:11 UTC, TNTrol commented on button_module/button_module.c
> +    m_operation ^= 0x1;
Исправил на логическую переменную и именнование тоже поменял в текущей версии оно стало полем, но данная строка выглядит вот так
https://github.com/TNTrol/ESTC-project/blob/be615bd498be6249fa07cb8a09aa7838154572e3/button_module/button_module.c#L18

2021-11-22 17:11 UTC, TNTrol commented on button_module/button_module.c
> +static nrfx_gpiote_evt_handler_t m_evt_handler = NULL;
Исправлено

2021-11-23 07:38 UTC, Diadlo commented on main.c
> +    m_state = m_state == V_MOD ? NONE : m_state + 1;
А почему макрос, а не функция?

2021-11-23 07:40 UTC, Diadlo commented on main.c
> +                h = h == 1023 ? 0 : h + 1;
1. Вопрос тот же. Почему не функция?
2. Может `CIRCLE`?
3. Что будет, если я сделаю `CICLE_INCREMENT(h, 1 << 10)`?

2021-11-23 21:02 UTC, TNTrol commented on main.c
> +                h = h == 1023 ? 0 : h + 1;
1. А есть смысл ее делать? Просто всего две операции и одна строчка. Если только сделать инлайн функцию. Или все же этот подход неверен?
2. Да, исправил, учу граммоту.
3. Увидел ошибку, поместил в скобочки операцию
Результат
https://github.com/TNTrol/ESTC-project/blob/7c586c82bad2a660d6d92149832c4d65f40d0d19/util_module/utils.h#L4

2021-11-24 12:01 UTC, Diadlo commented on main.c
> +                h = h == 1023 ? 0 : h + 1;
> А есть смысл ее делать?

Есть случаи, когда макрос может сделать то, что может сделать функция. Выполнять какие-то действия для переменных разных типов, производить стрингификацию токенов и т.п. Но если ничего из этого не нужно, то какие плюсы есть у макроса? Никаких. Зато минусов хоть отбавляй:

1. Не очевидные side effect'ы (можно поменять локальную переменную, которую не передавали)
2. Невозможность отладки.
3. При возникновении ошибки компиляции в сложном макросе в качестве строки с ошибкой вы получите просто строку с макросом, т.к. по сути он всегда однострочный.
4. Высокая вероятность ошибки из-за приоритетов операции
5. В случае если параметр используется в макросе дважды, а в качестве аргумента передать `i++`, то произойдет два инкремента.

Именно поэтому я ставлю вопрос именно как "зачем макрос?"/"почему не функция?"

2021-11-28 09:10 UTC, merged