add save state rgb
TNTrol/ESTC-project pull request #19
Opened 2021-11-28 21:26 UTC by TNTrol

2021-12-07 10:44 UTC, Diadlo requested changes

2021-12-07 10:44 UTC, Diadlo commented on color_module/color_module.c
> +    rgbMin = rgb->r < rgb->g ? (rgb->r < rgb->b ? rgb->r : rgb->b) : (rgb->g < rgb->b ? rgb->g : rgb->b);
Подумайте, это никак нельзя упростить?

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +        temp = word[i] - 48;
Что за `48`? Может лучше `42`?)
Вообще если вы хотите использовать код символа, то можете просто делать `word[i] - '0'`

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +        if(temp > 255 - number * 10)
Почему именно 255? Если вам нужно максимальное значение u8, то можете использовать `UINT8_MAX`

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +bool parse_chars_to_uint8(const char *word, uint8_t size, uint8_t *out)
Если надо распарсить число из строки, то лучше использовать `strtoi`, `strtol` и другие, а не писал эту логику с нуля

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +uint8_t cmp_chars(const char *s1, const char *s2, uint8_t size)
См. `strncmp`

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +bool convert_command1(const char *word, uint8_t *index)
Чисто как вариант, вы можете вернуть `uint8_t`, где `UINT8_MAX` будет обозначать ошибку разбора. Или `uint16_t`, тогда `UINT8_MAX` будет корректным, а вот `UINT8_MAX + 1` уже не корректным

И что означает суффикс `1` в имени?

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +        m_callback(m_state, 255, 0);
Почему именно `255`? Что это за число?
Не передавайте `0` вместо указателя, лучше использовать `NULL`

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +        parse_chars_command();
А почему функция `print_char` вызывает `parse_chars_command`, которая потом вызовет еще и callback из основной программы? Вам не кажется, что функция выполняет больше, чем печатанье символа?

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.h
> +#define COUNT_WORD 4
Это решение очень сильно заточено на задачу. Буквально добавление новой команды и придется тут все править. Вот появится команда в 20 символов длиной и одним параметром или в 3 символа и 20 параметров. Подумайте, нельзя ли как-то лучше сорганизовать процесс разбора команды. Будут вопросы -- пишите

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.h
> +    const uint8_t count_argument;//--3
А если будет команда с переменным числом аргументов?

2021-12-07 10:44 UTC, Diadlo commented on usb_module/usb_module.c
> +                m_callback(index == 1, args[0], args[1], args[2]);
Вот так всегда. Вроде как надо указать число аргументов, а тут их всегда 3)

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +static function_command m_callback = 0;
В качестве указателя лучше использовать `NULL`. Технически адрес представим как число и нулевой адрес действительно это 0, но с логической точки зрения это разные сущности. Это как присваивать километры в секунды. Поэтому лучше если нужен не валидный указатель использовать именно `NULL`

2021-12-07 10:44 UTC, Diadlo commented on convert_module/convert_cmd.c
> +static uint8_t m_args[COUNT_WORD - 1];
А если аргумент будет uint32? Или строковым?

2021-12-07 10:44 UTC, Diadlo commented on usb_module/usb_module.c
> +static command_t m_commands[] = {{.name = "HSV\0", .count_argument = 3}, {.name = "RGB\0", .count_argument = 3}, {.name = "help\0", .count_argument = 0}};
Не надо добавлять `\0` ко всем строкам. Стандартный строковый литерал в С и так заканчивается `\0`

2021-12-07 10:44 UTC, Diadlo commented on usb_module/usb_module.h
> +#include "../convert_module/convert_cmd.h"
Не надо добавлять в заголовок include, которые не нужны в этом заголовке. Если у вас будет изменение в `convert_cmd.h`, то пересобирать придется все, что инклудит `usb_module.h` даже если они не зависят никак от `convert_cmd.h`. То же самое касается `nrf_log` тут

2021-12-07 18:57 UTC, TNTrol commented on convert_module/convert_cmd.c
> +static function_command m_callback = 0;
Исправил, понимаю в чем разность, но просто у меня vscode ругался на NULL(нашел баг) и так избавлялся от лишних предупреждений ибо отвлекают. Понимаю что на прод или как код для ревью такое нельзя вообще показывать(про внутренние костыли)

2021-12-07 19:02 UTC, TNTrol commented on usb_module/usb_module.c
> +static command_t m_commands[] = {{.name = "HSV\0", .count_argument = 3}, {.name = "RGB\0", .count_argument = 3}, {.name = "help\0", .count_argument = 0}};
Исправил. Когда делал не был достаточно эрудирован по данному вопросу. Но восполнил данный пробел

2021-12-07 19:04 UTC, TNTrol commented on usb_module/usb_module.h
> +#include "../convert_module/convert_cmd.h"
Исправил. Полностью согласен и понимаю почему это так.

2021-12-07 23:06 UTC, TNTrol commented on color_module/color_module.c
> +    rgbMin = rgb->r < rgb->g ? (rgb->r < rgb->b ? rgb->r : rgb->b) : (rgb->g < rgb->b ? rgb->g : rgb->b);
Использую теперь макросы https://github.com/TNTrol/ESTC-project/blob/10e4316c2047e692636c3c9ac8b97e33d9ebe04a/color_module/color_module.c#L58
https://github.com/TNTrol/ESTC-project/blob/10e4316c2047e692636c3c9ac8b97e33d9ebe04a/color_module/color_module.c#L59

2021-12-08 01:03 UTC, TNTrol commented on convert_module/convert_cmd.c
> +uint8_t cmp_chars(const char *s1, const char *s2, uint8_t size)
Исправил.
https://github.com/TNTrol/ESTC-project/blob/bfe29aff0b4784745dbc6626d646e3219e76b7e0/convert_module/convert_cmd.c#L41

2021-12-08 08:54 UTC, TNTrol commented on convert_module/convert_cmd.c
> +        if(temp > 255 - number * 10)
https://github.com/TNTrol/ESTC-project/blob/bfe29aff0b4784745dbc6626d646e3219e76b7e0/convert_module/convert_cmd.c#L26

2021-12-08 08:55 UTC, TNTrol commented on convert_module/convert_cmd.c
> +bool parse_chars_to_uint8(const char *word, uint8_t size, uint8_t *out)
Ну в моем решении у них есть некоторый недостаток. Пытался использовать strtol, но возникли трудности.

2021-12-08 08:58 UTC, TNTrol commented on convert_module/convert_cmd.c
> +bool convert_command1(const char *word, uint8_t *index)
Поменял на uint8_max
https://github.com/TNTrol/ESTC-project/blob/7f908bb48ace7b71c310d9c8cb030f0ab9d2d3b3/convert_module/convert_cmd.c#L53
Цифра 1 осталось с момента продумывания, забыл убрать

2021-12-08 08:59 UTC, TNTrol commented on convert_module/convert_cmd.c
> +        m_callback(m_state, 255, 0);
Поменял на uint9_max и на NULL
https://github.com/TNTrol/ESTC-project/blob/7f908bb48ace7b71c310d9c8cb030f0ab9d2d3b3/convert_module/convert_cmd.c#L53

2021-12-08 09:00 UTC, TNTrol commented on convert_module/convert_cmd.c
> +        parse_chars_command();
Да, название плохое, переименовал 
https://github.com/TNTrol/ESTC-project/blob/7f908bb48ace7b71c310d9c8cb030f0ab9d2d3b3/convert_module/convert_cmd.c#L85
Думаю как разъединить логику

2021-12-08 09:04 UTC, TNTrol commented on convert_module/convert_cmd.h
> +    const uint8_t count_argument;//--3
Есть мысль, чтобы хранить максимально количество и минимальное

2021-12-08 09:06 UTC, TNTrol commented on usb_module/usb_module.c
> +                m_callback(index == 1, args[0], args[1], args[2]);
Что Вы имеете в виду? Нужно использовать колбэк с произвольным кол-вом параметров?

2021-12-08 09:13 UTC, TNTrol commented on convert_module/convert_cmd.c
> +static uint8_t m_args[COUNT_WORD - 1];
Если честно, то для этой задачи решил считать что аргументы только числовые. Ну такое упрощение, хотя была идея сделать массив uint8_t длиннее и записывать данные туда. И создать структуру для хранения:
struct {
const *uint8_t arg;
uint8_t size;
}

2021-12-08 09:32 UTC, TNTrol commented on convert_module/convert_cmd.h
> +#define COUNT_WORD 4
Ну тут как бы была попытка сделать гибкое решение, просто чтобы знать максимальное кол-во слов в команде и сколько максимум символов в слове, а так можно поменять эти числа и работает. Но соглашусь что не идеально. Вообще была идея(отказался потому что подумал что это костыльно) сделать достаточно большой массив чаров для хранения строки которая до \n и после парсить не слова отдельно а строку. Тогда это подходит под ваши замечания. Тогда переделаю.

2021-12-08 09:33 UTC, TNTrol commented on convert_module/convert_cmd.c
> +        temp = word[i] - 48;
Исправил
https://github.com/TNTrol/ESTC-project/blob/bfe29aff0b4784745dbc6626d646e3219e76b7e0/convert_module/convert_cmd.c#L26

2021-12-08 12:56 UTC, TNTrol commented on convert_module/convert_cmd.c
> +static uint8_t m_args[COUNT_WORD - 1];
А так в идеале структура команды должна иметь свой конвертер аргументов (должен быть указатель на функцию)

2021-12-09 07:39 UTC, Diadlo commented on usb_module/usb_module.c
> +                m_callback(index == 1, args[0], args[1], args[2]);
Ну, как минимум можно передать указатель на массив и число элементов. А то совсем не честно, число параметров указывать надо, а принимать всегда должен три.

2021-12-09 07:40 UTC, Diadlo commented on convert_module/convert_cmd.c
> +static uint8_t m_args[COUNT_WORD - 1];
Если вы осознано приняли такое решение исходя из текущих требований -- ок, можете оставить как есть

2021-12-09 07:41 UTC, Diadlo commented on convert_module/convert_cmd.c
> +bool parse_chars_to_uint8(const char *word, uint8_t size, uint8_t *out)
Какие?

2021-12-09 07:56 UTC, Diadlo commented on color_module/color_module.c
> +#define min(a,b) ((a)<(b)?(a):(b))
Макросы лучше именовать большими буквами, чтобы в месте использования было понятно, что это не функция

2021-12-09 07:56 UTC, Diadlo commented on convert_module/convert_cmd.c
> +    if(index == UINT8_MAX)
В целом это гараздо лучше. Но еще можно добавить где-нибудь `#define INDEX_NOT_FOUND UINT8_MAX` и сравнивать именно в такой константой. На ваше усмотрение

2021-12-09 07:56 UTC, Diadlo commented on convert_module/convert_cmd.c
> +        if(temp > UINT8_MAX - number * 10 || word[i] > '9' || word[i] < '0')
См. `isdigit`

2021-12-09 09:59 UTC, TNTrol commented on convert_module/convert_cmd.c
> +bool parse_chars_to_uint8(const char *word, uint8_t size, uint8_t *out)
По той схеме парсинга команды, я не мог точно сказать что все хорошо идет, сейчас исправляю с учетом лекции и все норм

2021-12-11 23:39 UTC, TNTrol commented on command_module/command.h
> +    char line[COMMAND_BUFFER];
Думаю стоит тут указатель на массив хранить, тем самым сделав данный контекст более гибким

2021-12-11 23:40 UTC, TNTrol commented on convert_module/convert_cmd.c
> +        if(temp > UINT8_MAX - number * 10 || word[i] > '9' || word[i] < '0')
Почитал про подобные макрос, но уже он не нужен, от такого рода парса я отказался в пользу стандартных функций

2021-12-11 23:41 UTC, TNTrol commented on convert_module/convert_cmd.c
> +    if(index == UINT8_MAX)
Спасибо за совет, воспользовался

2021-12-11 23:47 UTC, TNTrol commented on color_module/color_module.c
> +#define min(a,b) ((a)<(b)?(a):(b))
Исправил

2021-12-13 10:36 UTC, Diadlo commented on main.c
> +    for(uint8_t i = 0; i < 3; ++i)
Почему именно 3? А если я захочу распарсить 2 или 4 элемента?

2021-12-13 10:36 UTC, Diadlo commented on main.c
> +        usb_write_msg("\r\nUnexpected count arguments\n\r", 30);
А нельзя как-то сделать так, чтобы не надо было считать символы?

2021-12-13 10:36 UTC, Diadlo commented on main.c
> +    init_parse(sizeof(m_commands) / sizeof(command_t), m_commands, handler_unknown_command);
Вы можете использовать макрос `ARRAY_SIZE(m_commands)`

2021-12-13 11:03 UTC, TNTrol commented on main.c
> +    for(uint8_t i = 0; i < 3; ++i)
Если честно, то ide, где я тестировал функции для команды, рекомендовало исправить и я поддался искушению дать разрешение на авторефакторинг)))))
Но исправил

2021-12-13 11:04 UTC, TNTrol commented on main.c
> +        usb_write_msg("\r\nUnexpected count arguments\n\r", 30);
Да, можно. Добавил в usb_module подсчет символов с помощью встроенной функции

2021-12-13 11:05 UTC, TNTrol commented on main.c
> +    init_parse(sizeof(m_commands) / sizeof(command_t), m_commands, handler_unknown_command);
Спасибо за совет. Воспользовался

2021-12-15 08:05 UTC, merged